# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            #memory: ~
            memory:

                users:
                    moritz:
                        password: Lacertae66Mag
                        roles: 'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

        #Symfony\Component\Security\Core\User\User:
        #  algorithm: bcrypt
        #  cost: 12
        ## to crate a bcrypted password use: php bin/console security:encode-password

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            form_login:
              login_path: login
              check_path: login


            logout:
              path:   /logout
              target: /


    access_control:
        # require ROLE_ADMIN for some subpages
        - { path: ^/domain, roles: ROLE_ADMIN }
        - { path: ^/account, roles: ROLE_ADMIN }
        - { path: ^/alias, roles: ROLE_ADMIN }
